name: Build macOS DMG (Hello App, safe)

on:
  workflow_dispatch:  # you run it manually

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # Build in a separate folder so your repo contents can't break the build
      - name: Bootstrap hello app
        run: |
          mkdir -p hello/electron hello/public
          cd hello
          cat > package.json << 'JSON'
          {
            "name": "lecuredesign-electron",
            "version": "0.0.1",
            "private": true,
            "main": "electron/main.js",
            "type": "module",
            "scripts": { "build:app": "electron-builder --mac dmg --arm64 -c.mac.identity=null -c.dmg.artifactName='LeCureDesign-${version}-mac-arm64.${ext}'" },
            "devDependencies": { "electron": "31.2.0", "electron-builder": "24.13.3" }
          }
          JSON

          cat > electron/main.js << 'JS'
          import { app, BrowserWindow } from 'electron'
          app.whenReady().then(() => {
            const win = new BrowserWindow({ width: 900, height: 600 })
            win.loadFile('public/index.html')
          })
          JS

          cat > public/index.html << 'HTML'
          <!doctype html><html><head>
            <meta charset="utf-8"/><title>LeCureDesign</title>
            <style>body{font:16px system-ui;margin:24px}h1{margin:0 0 8px}</style>
          </head><body>
            <h1>LeCureDesign Installer</h1>
            <p>✅ This verifies your DMG pipeline works. You can install this on your Mac.</p>
          </body></html>
          HTML

      - name: Install deps
        run: cd hello && npm install --no-audit --no-fund

      - name: Build DMG (arm64)
        run: cd hello && npm run build:app

      - name: List dist
        run: ls -la hello/dist || true

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: LeCureDesign-DMG
          path: hello/dist/*.dmg

      - name: Create GitHub Release (auto-tag)
        if: hashFiles('hello/dist/*.dmg') != ''
        uses: softprops/action-gh-release@v2
        with:
          files: hello/dist/*.dmg
          tag_name: v${{ github.run_number }}
          name: "LeCureDesign v${{ github.run_number }}"
          generate_release_notes: true
