name: Release macOS DMG
on:
  workflow_dispatch:
  push:
    tags: ['v*']
permissions:
  contents: write
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps
        run: npm ci
      - name: Build Next.js
        run: npm run build:web
      - name: Build DMG
        run: npm run build:app
        env:
          NEXT_PUBLIC_REGION: EU-IT
          NEXT_PUBLIC_CURRENCY: EUR
      - uses: actions/upload-artifact@v4
        with: { name: dmg, path: dist/*.dmg }
      - if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with: { files: dist/*.dmg }
